### ISSUE TITLE
PCC nur als default admin erreichbar

### ISSUE THREAD

**Issue by rmjspa** [agent4788/SHC_Framework#106]
Trotz mehrerer frischer Installationen lässt sich das PCC nicht von neu angelegten Usern mit Administrationsrechten erreichen. Nur vom default admin.
Vielleicht sollte man es wieder in SHC integrieren und wer es nicht mag / möchte kann es in den Einstellungen deaktivieren.

**Comment by agent4788** [comment]
Du musst der Admin Gruppe erst noch die Berechtigungen geben. Beim installieren werden allen Gruppen die selben Standard Rechte vergeben.

**Comment by agent4788** [comment]
In der Install werden die neuen Rechte nicht gespeichert
