### ISSUE TITLE
schaltbares Element für Funkdimmer

### ISSUE THREAD

**Issue by agent4788** [agent4788/SHC_Framework#13]

**Comment by jens-pfeiffer** [comment]
Kommt die Funktion doch in 2.2

**Comment by agent4788** [comment]
nein, da ich keine Funksteckdose zum testen habe kommt das erst mit 2.4

**Comment by jens-pfeiffer** [comment]
Zur Funktion ein Dimmer wird gedimmt durch mermaliegen Drucker der taste

**Comment by agent4788** [comment]
Ich weiß, aber ohne soetwa Testen zu können kann ich nur schwer eine brauchbare voreinstellung treffen und sinnvolle Grenzen festlegen.

**Comment by jsp-email** [comment]
Wie wirst du es den machen per schiebebutton oder

**Comment by agent4788** [comment]
Ja
