### ISSUE TITLE
Sensor einlesen sensor sender läuft nicht

### ISSUE THREAD

**Issue by jonny1995** [agent4788/SHC_Framework#14]
nach dem befehl /var/www/shc $ php index.php app=shc -st -addDHT 88 22 7
88=id
22=type
7=gpio
"DHT erfolgreich erstellt"
danach steht in der weboberfläche das sensor sender nicht läuft und der sensor wird nicht angezeigt
in der datei "sensortransmitter.xml" steht <dht><id>88</id><type>22</type><pin>7</pin><name/></dht>
nehme ich  das wieder raus geht der sensor sender nach einem neustart wieder 
was mache ich falsch ?

**Comment by agent4788** [comment]
starte den Sensorsender mal wie folgt von Hand und Schau mal nach der Fehlermeldung warum der abstürzt.

```
php index.php app=shc -st -d
```

wenn du nicht weiter kommst schreibe hier einfach mal die Fehlermeldung rein

**Comment by jonny1995** [comment]
hab jetzt alles wie in der beschreibung "sensoren" gemacht.
hier die fehlermeldung:
![fehlermeldung](https://cloud.githubusercontent.com/assets/10107343/5339088/38a1cefc-7edc-11e4-9d6e-ba196650edd9.PNG)

**Comment by agent4788** [comment]
Da hat sich wohl noch ein kleiner Fehler versteckt, der wird mit dem nächsten update gefixt
