### ISSUE TITLE
orderId Sortierung 

### ISSUE THREAD

**Issue by arteck** [agent4788/SHC_Framework#154]
PHP Warning

Illegal string offset 'orderId'
File:   /var/www/shc/shc/lib/view/room/viewhelpereditor.class.php
Line:   318
Code:   2
Stack:  
#0 /var/www/shc/shc/lib/view/room/viewhelpereditor.class.php @ Line: 318

```
RWF\Error\Error->handlePhpError(2, 'Illegal string offset 'orderId'', '/var/www/shc/shc/lib/view/room/viewhelpereditor.class.php', 318, Array(5))
```
#1 /var/www/shc/shc/data/commands/web/acp/switchables/saveswitchableorderaction.class.php @ Line: 143

```
SHC\View\Room\ViewHelperEditor->editBoxOrder(Array(3))
```
#2 lib/request/commands/actioncommand.class.php @ Line: 31

```
SHC\Command\Web\SaveSwitchableOrderAction->executeAction()
```
#3 lib/request/abstractcommand.class.php @ Line: 77

```
RWF\Request\Commands\ActionCommand->executeCommand()
```
#4 lib/request/requesthandler.class.php @ Line: 184

```
RWF\Request\AbstractCommand->execute(RWF\Request\HttpRequest, RWF\Request\HttpResponse)
```
#5 lib/request/requesthandler.class.php @ Line: 133

```
RWF\Request\RequestHandler->handleWebRequest('action...', 'saveswitchableorder...')
```
#6 lib/request/requesthandler.class.php @ Line: 95

```
RWF\Request\RequestHandler->__construct('action...', 'saveswitchableorder...')
```
#7 /var/www/shc/index.php @ Line: 25

```
RWF\Request\RequestHandler::handleRequest()
```
#8 {main}

**Comment by agent4788** [comment]
Fix ist schon im Issue #153 mit enthalten

**Comment by arteck** [comment]
nach update immer noch da.. ich kann keine Boxen verschieben

**Comment by rgarcia89** [comment]
Ich kann das ganze bestätigen. 
Klickt man nach dem verschieben auf bestätigen, erhält man nach wie vor die oben beschriebene Meldung
