### ISSUE TITLE
Mobil Oberfläche Error beim Serverstartus

### ISSUE THREAD

**Issue by agent4788** [agent4788/SHC_Framework#156]
ystem Error

Die Klasse "SHC\Command\Smartphone\XmlEditor" konnte nicht gefunden werden
Klasse: SHC\Command\Smartphone\XmlEditor
File:   lib/classloader/classloader.class.php
Line:   288
Code:   1001
Stack:  
#0 global.php @ Line: 86

```
RWF\ClassLoader\ClassLoader->loadClass('SHC\Command\Smartphone\XmlEditor')
```
#1 /media/projects/PHP/shcFramework/shc/data/commands/smartphone/acp/daemonstatepage.class.php @ Line: 131

```
__autoload('SHC\Command\Smartphone\XmlEditor')
```
#2 lib/request/commands/pagecommand.class.php @ Line: 45

```
SHC\Command\Smartphone\DaemonStatePage->processData()
```
#3 lib/request/abstractcommand.class.php @ Line: 77

```
RWF\Request\Commands\PageCommand->executeCommand()
```
#4 lib/request/requesthandler.class.php @ Line: 184

```
RWF\Request\AbstractCommand->execute(RWF\Request\HttpRequest, RWF\Request\HttpResponse)
```
#5 lib/request/requesthandler.class.php @ Line: 133

```
RWF\Request\RequestHandler->handleWebRequest('page...', 'daemonstate...')
```
#6 lib/request/requesthandler.class.php @ Line: 91

```
RWF\Request\RequestHandler->__construct('page...', 'daemonstate...')
```
#7 /media/projects/PHP/shcFramework/index.php @ Line: 25

```
RWF\Request\RequestHandler::handleRequest()
```
#8 {main}

**Comment by rgarcia89** [comment]
http://raspberrypi03.lan/shc/index.php?app=shc&page=daemonstate
Führt seit dem Update bei mir auf eine leere Seite - egal ob mit dem Internet Explorer, Edge oder Chrome

**Comment by agent4788** [comment]
Schaue mal in die Apache Error Log da muss es eine Fehlermeldung geben. Die Leere Seite ist nur weil dein Webserver so konfiguriert ist Fehlermeldungen nicht aus zu geben sondern zu loggen (default Einstellung).

**Comment by rgarcia89** [comment]
@raspberrypi03 /var/log/apache2 $ cat error.log
[Tue Sep 22 07:16:47 2015] [notice] Apache/2.2.22 (Debian) PHP/5.4.45-0+deb7u1 configured -- resuming     normal operations
[Tue Sep 22 07:19:40 2015] [error] [client 192.168.1.100] PHP Fatal error:  Call to a member function     format() on a non-object in /var/www/shc/rwf/lib/date/datetime.class.php on line 113, referer: http://    raspberrypi03.lan/shc/index.php
