### ISSUE TITLE
Fehler in der CLI Hilfe

### ISSUE THREAD

**Issue by agent4788** [agent4788/SHC_Framework#157]
ystem Error

Die Klasse "SHC\Command\Smartphone\XmlEditor" konnte nicht gefunden werden
Klasse: SHC\Command\Smartphone\XmlEditor
File:   lib/classloader/classloader.class.php
Line:   288
Code:   1001
Stack:  
#0 global.php @ Line: 86

```
RWF\ClassLoader\ClassLoader->loadClass('SHC\Command\Smartphone\XmlEditor')
```
#1 /media/projects/PHP/shcFramework/shc/data/commands/smartphone/acp/daemonstatepage.class.php @ Line: 131

```
__autoload('SHC\Command\Smartphone\XmlEditor')
```
#2 lib/request/commands/pagecommand.class.php @ Line: 45

```
SHC\Command\Smartphone\DaemonStatePage->processData()
```
#3 lib/request/abstractcommand.class.php @ Line: 77

```
RWF\Request\Commands\PageCommand->executeCommand()
```
#4 lib/request/requesthandler.class.php @ Line: 184

```
RWF\Request\AbstractCommand->execute(RWF\Request\HttpRequest, RWF\Request\HttpResponse)
```
#5 lib/request/requesthandler.class.php @ Line: 133

```
RWF\Request\RequestHandler->handleWebRequest('page...', 'daemonstate...')
```
#6 lib/request/requesthandler.class.php @ Line: 91

```
RWF\Request\RequestHandler->__construct('page...', 'daemonstate...')
```
#7 /media/projects/PHP/shcFramework/index.php @ Line: 25

```
RWF\Request\RequestHandler::handleRequest()
```
#8 {main}

**Comment by agent4788** [comment]
gleicher Fehler wie im Issue #156 beschrieben

**Comment by rgarcia89** [comment]
Die Anwendung von Issue 156 hat bei mir nicht zur Lösung des Problems geführt. Stattdessen kommt nun folgende Fehlermeldung:

pi@raspberrypi03 /var/www/shc $ php index.php app=shc -h
-sw oder --switch

Mit diesem Befehl kann man schaltbare Elemente über die Kommandozeile schalten

Erforderliche Parameter:
        id=<Element ID>
                die ID des zu schaltenden Elementes
        --on oder --off oder --toggle
                der Befehl der ausgeführt werden soll
                --on Einschalten
                --off Ausschalten
                --toggle Umschalten
Zusätzliche Optionen:
        -l oder --list
                gibt eine Liste mit allen verfuegbaren Elemeten un deren ID aus
-ds oder --daemonstate gibt eine Liste mit den Diensten und ihrem Status aus

Der Daemon Status gibt eine Liste mit allen Diensten und ihrem Status aus

PHP Fatal error:  Call to a member function loadModul() on a non-object in /var/www/shc/shc/data/commands/cli/switchservercli.class.php on line 79

Ich kann somit auch noch nicht bestätigen ob der ST wieder läuft. -ds zeigt nämlich nach wie vor folgenden Fehler an:
php index.php app=shc -ds
PHP Fatal error:  Call to a member function getValue() on a non-object in /var/www/shc/rwf/lib/core/rwf.class.php on line 396
