### ISSUE TITLE
Schaltbare Elemente sortieren

### ISSUE THREAD

**Issue by rgarcia89** [agent4788/SHC_Framework#161]
Hallo,

das verschieben von Schaltbare Elemente elementen ist im aktuellen Development branche nicht möglich. Apache Fehler Log sieht wie folgt aus:

[Tue Sep 22 22:42:03 2015] [error] [client 192.168.1.115] PHP Fatal error:  Call to undefined method RWF\Request\SSEResponse::addRetry() in /var/www/shc/shc/data/commands/all/roomsync.class.php on line 111, referer: http://192.168.1.30/shc/index.php?app=shc&page=index

**Comment by agent4788** [comment]
Der Fehler SSEResponse::addRetry() wurde schon gemeldet und behoben. Warum aber das verschieben nicht gehen soll ist unklar, da dieser fehler mit der ACP Oberfläche nichts zu tun hat. Bei mir auf dem Testsystem konnte ich jetzt keinen Fehler feststellen.

**Comment by rgarcia89** [comment]
Okay ich habe eben noch mal ein wenig genauer geschaut. Das Problem liegt nur vor wenn ich versuche ein DHT11/22 Sensor in der Sortierung zu verschieben. Funksteckdosen und GPIO Eingänge lassen sich verschieben und bleiben nach dem Klick auf Speichern auch an der neuen Position. Die DHT Sensoren hingegen springen zurück an die Position an der sie vorher standen...
Ein Fehler wird dabei leider weder in der apache log noch in den SHC logs gemeldet. 
Ich habe das ganze mit Chrome, Edge und dem Internet Explorer getestet
