### ISSUE TITLE
fatal error server status

### ISSUE THREAD

**Issue by arteck** [agent4788/SHC_Framework#163]
Fatal error: Call to a member function format() on a non-object in /var/www/shc/rwf/lib/date/datetime.class.php on line 113

nachdem ich die Einstellung geändert habe unter Datum Uhrzeit

**Comment by agent4788** [comment]
Was hast du auf welchen wert gestellt?

**Comment by agent4788** [comment]
der Fehler sollte mit dem Issue #159 erledigt sein
