### ISSUE TITLE
Users at Home zeigt immer alle Benutzer als da an

### ISSUE THREAD

**Issue by Microgamer** [agent4788/SHC_Framework#179]
Ping gibt auch etwas zurück, wenn er nicht erfolgreich war.

**Comment by jsp-email** [comment]
Bei mir macht er es nicht

**Comment by Microgamer** [comment]
Erstell mal ne PHP-Datei mit folgendem Inhalt:
<?php                                                                   error_reporting('E_ALL');
echo strlen(exec(sprintf('ping -c 1 -W 1 192.168.178.31')));
?>
Ersetze 192.168.178.31 durch ne IP, die bei dir nicht existiert.
Und schicke mal die Ausgabe, die sein Browser anzeigt.

**Comment by Microgamer** [comment]
Ach ich sehe grade, dass der Code doch stimmt...
Ich hab nur ne IP eingegeben, die bei mir existiert hat...

**Comment by jsp-email** [comment]
0

----- Ursprüngliche Nachricht -----

Von: Microgamer &lt;notifications@github.com>

Gesendet: 06. Dez. 2015 17:32

An: &quot;agent4788/SHC_Framework&quot; &lt;SHC_Framework@noreply.github.com>

Betreff: Re: [SHC_Framework] Users at Home zeigt immer alle Benutzer als da an (#179)

Erstell mal ne PHP-Datei mit folgendem Inhalt:

&lt;?php                                                                   error_reporting('E_ALL');

echo strlen(exec(sprintf('ping -c 1 -W 1 192.168.178.31')));

?>

Ersetze 192.168.178.31 durch ne IP, die bei dir nicht existiert.

Und schicke mal die Ausgabe, die sein Browser anzeigt.

—
Reply to this email directly or  view it on GitHub (https://github.com/agent4788/SHC_Framework/issues/179#issuecomment-162327317" target="_blank).<img alt="" height="1" src="https://github.com/notifications/beacon/AFroz_L3j2CxfepfpJFQQZocdrwcldkeks5pNFqBgaJpZM4Gvov-.gif" width="1" />

----- Ursprüngliche Nachricht Ende -----

## 

Alle Postfächer an einem Ort. Jetzt wechseln und E-Mail-Adresse mitnehmen!  Rundum glücklich mit freenetMail (https://email.freenet.de/basic/Informationen" target="_blank)

**Comment by agent4788** [comment]
Ich schaue noch einmal ob sich ohne viel Aufwand der Fehler beheben lässt. Da der neue Scheduler mit sicherheit nicht vor Anfang/Mitte kommenden Jahres stabil laufen wird.

**Comment by Microgamer** [comment]
Agent es geht doch alles... Es scheint nur ein Problem von einer Person zu sein (schau mal ins Forum)
Ich mache den mal zu, weil der Bug vermutlich ein Einzelfall ist.

**Comment by jsp-email** [comment]
Hello,

There are a cople of stories I wanted to share with you, please, read more here <http://chashatriche.trump-scarborough2016.org/aeaasf?6r>

Be well, jsp-email@freenet.de

**Comment by jsp-email** [comment]
Hello, 


We haven't talked for a while so I just wanted to say Hi and share with you  some information, read more here please <http://permit.westclermontlevy.com/aeayjo>

Sent from a prehistoric stone tablet, jsp-email
