### ISSUE TITLE
Abfrage shc/data/log

### ISSUE THREAD

**Issue by Dietmar-Franken** [agent4788/SHC_Framework#181]
Bitte die abfrage für shc/data/log herausnehmen in  /shc/index.php?app=shc&page=info.
Wird ja nicht mehr benötigt,wie ich im Forum gelesen habe.
http://rpi-controlcenter.de/showthread.php?tid=519&pid=4466#pid4466

**Comment by agent4788** [comment]
Ganz entfernen kann ich den Ordner nicht so einfach, ich habe jetzt nur geändert das er automatisch mit erstellt wird -> https://github.com/agent4788/SHC_Framework/commit/881651849af6c33eff3556350e9d9f37c8479e52
