### ISSUE TITLE
v2.2.5 Scripte werden nicht ausgeführt

### ISSUE THREAD

**Issue by thekk1** [agent4788/SHC_Framework#183]
Scripte werden nicht durch den Scheduler ausgeführt.
Siehe:
http://rpi-controlcenter.de/showthread.php?tid=635&pid=4512#pid4512

**Comment by agent4788** [comment]
Wenn Scripte vom Scheduler nicht ausgeführt werden liegt das entweder an falschen Berechtigungen oder Fehlern im Script selbst. Scripte werden mit unterschiedlichen Rechten ausgeführt bei der Weboberfläche www-data und beim Scheduler der Systembenutzer.
