### ISSUE TITLE
Fehler bei der Installation

### ISSUE THREAD

**Issue by Bratze** [agent4788/SHC_Framework#214]
Hallo,

ich bin hier echt komplett neu und wahrscheinlich auch nicht ganz auf dem richtigen weg (?!) aber ein Nachrichtensystem in dem ich anschreiben hätte können gibt es hier garnicht (bitte entschuldigt, ich bin hier ein über-ober-voll-noob)?!

Als erstes nehme ich aber mal an das agent 4788 das hier alles rein privat gemacht hat und möchte hier respekt und anerkennung aussprechn (auch den ggf. vorhandenen helfern).

Falls mir jemand mit engagement und professionalität hefen möchte vergebe ich gerne auch einen bezahlten auftrag (stummer schrei nach hilfe?!).

Sei es drum, was mir aufgefallen ist:

Auf dieser[Seite](https://github.com/agent4788/SHC_Framework/wiki/Raspberry-Pi) ist die Installation von SHC erklärt.

**unter dem Punkt 4** ist die Ramdisk erläutert, toll wäre hier auch der befehl (stimmt das so überhaupt?!)

`sudo mkdir /var/www/shc/rwf/data/cache`
`sudo nano tmpfs /var/www/shc/rwf/data/cache tmpfs nosuid,size=5M 0 0`
`sudo mount -a`

Der Erfolg lässt sich mit Diskfree überprüfen:
`df`

Es sollte dann ein Eintrag mit der RAM-Disk zu finden sein:

> Filesystem 1K-blocks Used Available Use% Mounted on
> rootfs 15071704 2734624 11674436 19% /
> /dev/root 15071704 2734624 11674436 19% /
> devtmpfs 218620 0 218620 0% /dev
> tmpfs 44580 236 44344 1% /run
> tmpfs 5120 0 5120 0% /run/lock
> tmpfs 89140 0 89140 0% /run/shm
> /dev/mmcblk0p1 57288 19712 37576 35% /boot
> tmpfs 5120 0 5120 0% /var/www/shc/rwf/data/cache

Jetzt ist nur noch zu prüfen, ob dies auch nach einem Reboot funktioniert:
`sudo reboot`

Mit Diskfree sollte jetzt die RAM-Disk wieder zu finden sein.
Jetzt ist zu testen, ob man Verzeichnisse und Dateien anlegen kann:

```
cd /var/www/shc/rwf/data/cache
sudo mkdir testvz1
sudo mkdir testvz2
sudo touch file1
cd testvz1
sudo touch file2
```

Der "sudo"-Befehl wird benötigt, weil das Dateisystem 'root' gehört. Anschließend kann man mit 
`ls -al`

ansehen, ob es funktioniert hat. Nach
`sudo reboot`

sind alle Verzeichnisse und Dateien verschwunden. Man muss sie also immer nach einem Reboot anlegen bzw. hineinkopieren.

unter **Punkt 5** SHC und PCC Installation ist mir auch ein bisschen was aufgefallen:

```
~ & cd /var/www
/var/www $ sudo git clone https://github.com/agent4788/SHC_Framework
/var/www $ sudo mv SHC_Framework/ shc/
/var/www $ cd shc/
/var/www/shc $ sudo chmod 0777 -R ./
/var/www/shc $ php install.php
/var/www/shc $ sudo chmod 0777 -R ./
```

Vielleicht bin ich ja aber auch schlicht und einfach auf dem falschen Pfad?!

Kann es sein das hier ein fehler bei den unterschiedlichen pfaden vorliegt?!
die install.php liegt bei mir nach diesem vorgehen unter /var/www/shc/SHC_Framework/install.php, da ist dann der befehl php install.php nich funktionsfähig, wenn ich ihn in diesem verzeichnich dann mache startet er, allerding (ich denke da liegt nun mein problem!?!?!?!?!?) frägt er eine ip, pwd und anderes ab und ich habe keinen plan was man da eintragen muss :(

kann mir hier jemand den weg aus der dunklen bzw. zur hellen Seite zeigen?!
wäre echt voll cooool, hab nämlich schon vier pis, 40 Relais und 10 taster in der wand und würde gerne ohne schramme am knie aus dem bett kommen.

Viel spass beim tüfteln,
Bratze

**Comment by rmjspa** [comment]
Komm doch mal ins Forum:
http://rpi-controlcenter.de
Da findest Du detaillierte Anleitungen und Fragen können da besser beantwortet werden.

**Comment by Bratze** [comment]
danke :)

mittlerweile komme ich immerhin schon mal zum login auf einer shc seite :)

muss mich mal nach standard logindaten (?!)

und den konfigurationsunterschieden zwischen server und client schlau machen.

gibt es da ein schema?! wenn ich es verstehen würde könnte ich ja mal eines erstellen ;)

**Comment by Bratze** [comment]
haha

admin admin :)

**Comment by rmjspa** [comment]
Der Unterschied zwischen Server und Cliente oder Slave und wie es installiert wird ist auch im oben benannten Forum beschrieben.
Da braucht man das hier nicht zumüllen.
