### ISSUE TITLE
es können keine negativen Temperaturwerte angezeigt werden

### ISSUE THREAD

**Issue by agent4788** [agent4788/SHC_Framework#24]

**Comment by rmjspa** [comment]
Also mit dem DHT22 werden mir negative Temperaturwerte angezeigt. Mit dem DS18x20 kann ich im Augenblick nicht testen.

**Comment by jens-pfeiffer** [comment]
DS18x20 werden noch keine minus grade angezeit,
Im shc steht temperatur auf 0.0 und dienst deaktiviett sich.

**Comment by agent4788** [comment]
- Stürzt der Dienst (Sensortransmitter) ab oder wird er eichtig deaktiviert? Das ist ein großer unterschied.
- Betrifft das nur DS18x20 Sensoren?
- welche Werte stehen in den Dateien des Sensors? SInd diese Negativ oder auch da schon 0.0

**Comment by rmjspa** [comment]
Der DHT22 zeigt richtig die negativen Temperaturen an. Habe ich, s.o. vor über zwei Wochen geschrieben.

**Comment by agent4788** [comment]
Hab ich gelesen, aber auch BMP Sensoren geben Temperaturen aus.

**Comment by rmjspa** [comment]
Das ist richtig. Der BMP Sensor schiesst aber den Sensortransmitterdes des SHC ab, so das der z.Z. gar nicht geht. Oder hat den jemand funktionstüchtig am laufen. Das würde mich dann sehr interessieren, wie er zu installieren ist. Die Adafruit Fehlermeldungen konnte ich beseitigen in dem ich die fehlenden Schritte in der Installationsanleitung ausgeführt habe. Mit den SHC Fehlermeldungen komme ich nicht weiter.

**Comment by agent4788** [comment]
Das der BMP nicht geht ist mir jetzt nicht geläufig. Schreibe das mal im Forum als eigenes Thema

**Comment by rmjspa** [comment]
Das der BMP nicht geht, habe ich schon mehrfach gepostet, im alten und neuen Forum. Zuletzt am 17.01.15 mit error log.
Es fehlen einige Schritte zur Installation in der Wiki. Danach konnte ich ihn manuel auslesen. Bei der Übergabe der Daten an den rwf (SHC), erwartet der SHC andere Daten und stürzt ab(der Sensortransmitter). Ich vermute mal, das wird mit dem DS18x20 so ähnlich sein, wenn der Wert (Temperatur) ein negatives Vorzeichen hat. Ich glaube mich erinnern zu können, dass der DS18x20 in der Version 1.2 auch nur null Grad angezeigt hat. Ich hatte damals den Sensor in eine Schale mit Ice cubes gelegt und mich gewundert, der Sache aber weiter keine Bedeutung zugemessen.
Mein Posting vom 17.01.2015 ist hier:

http://rpi-controlcenter.de/showthread.php?tid=39

Du hast auch damals geantwortet, bist aber nicht näher auf den Fehler eingegangen.

**Comment by jens-pfeiffer** [comment]
Wenn der Dienst deaktiviert wird dan steht da nur 0.0 c minus Zeichen steht da nicht

**Comment by jens-pfeiffer** [comment]
Eher er macht ein break

**Comment by jens-pfeiffer** [comment]
Wenn ich dan Sensor abklemme und den raspberry neu starte geht das wieder, bis ein Sensor wieder um die null Grad erreicht 
Immer bei den wert 0.0

**Comment by agent4788** [comment]
schaue mal bitte in der error.log ob da ein Fehler "Division by Zero" drin steht, wenn ja schreibe hiet mal die komplette Fehlermeldung rein.

und stehen bei negativen Temeraturen in der Datei "/sys/bus/w1/devices/<Sensor-ID>/w1_slave" ein negativer Wert?

**Comment by agent4788** [comment]
mit der neuen Sensorschnittstelle aus Issue #53 behoben
