### ISSUE TITLE
Schaltserver für den Banana Pi

### ISSUE THREAD

**Issue by agent4788** [agent4788/SHC_Framework#31]

**Comment by MikeOne86** [comment]
Hallo agent4788, weißt du schon ob es in diesem Jahr mit dem Banana Pi funktionieren wird?

**Comment by agent4788** [comment]
kann ich aktuell nicht sagen, Momentan verfüge ich auch noch nicht über die Hardware um überhaupt einen Schaltserver für den Banana Pi entwickeln zu können.

**Comment by agent4788** [comment]
es sind keine Anpassungen am SHC notwendig, es mussl lediglich statt wiringpi wiringBP verwendet werden (https://github.com/LeMaker/WiringBP)
