### ISSUE TITLE
BMP085 Sensor bringt Sensor- Transmitter zum Absturz 

### ISSUE THREAD

**Issue by rmjspa** [agent4788/SHC_Framework#56]
Erfassung der Daten im Adafruit Modul korrekt. Bei Übergabe der Daten an den Sensor- Transmittier stoppt dieser.

**Comment by agent4788** [comment]
Fix funltioniert nicht

**Comment by agent4788** [comment]
Zusätzlich scheint die Höhenberechnung nicht zu funktionieren

**Comment by rmjspa** [comment]
Ich glaube schon, dass sie funktioniert. Soweit ich mich erinnere, bezugnehmend des Posts von premo stimmt die Kommastelle des Luftdrucks nicht.

Zur Höhe habe ich etwas hier 
http://rpi-controlcenter.de/showthread.php?tid=26&page=4

Post #40 letzte Nacht etwas geschrieben.
