### ISSUE TITLE
Löschen von Ordnern in "Backup Verwaltung" nicht möglich

### ISSUE THREAD

**Issue by rmjspa** [agent4788/SHC_Framework#58]
Löschen von Dateien möglich. Ordner lassen sich nicht löschen.

**Comment by agent4788** [comment]
Die Ordner musst du von Hand löschen, das ist so nicht vorgesehen und auch nicht Möglich da du mit verschiedenen Benutzern arbeitest und somit die Berechtigungen fehlen..

Zudem wird ab Version 2.2 das Backup nur noch über Zip gepackte JSON Dateien behandelt, die auch direkt als Zip wieder hergestellt werden können. Damit entfällt auch das Unzip beim Backup wieder herstellen.

**Comment by rmjspa** [comment]
Wenn sich das ohnehin mit Ver. 2.2 ändert, ist das ok. Ansonsten fragt man sich, für was die roten Kreuzchen sind, wenn sie nicht funktionieren.

**Comment by agent4788** [comment]
Zum Löschen der Zip Dateien, wenn du über unzip auf der Kommandozeile die Zip Dateien entpckst ist das etwas anderes und so nicht im Programm implementiert.
