### ISSUE TITLE
Zeitgesteuertes Relais an GPIO schaltet, macht aber kein update in der GUI

### ISSUE THREAD

**Issue by rmjspa** [agent4788/SHC_Framework#59]
Folgende Situation: Schaltvorgang, zeitgesteuert Schaltet das Relais z. B. um 18:00 Uhr an und geht mit Sonnenaufgang um 07:15 Uhr aus. In der GUI bleibt es dann auf "Ein" stehen, ist aber aus. Dadurch wird dann um 18:00 Uhr kein neuer Schaltvorgang mehr ausgeführt. Tagsüber manuel ausschalten, obwohl es ja aus ist, dann geht es auch Abends wieder an.
Das gilt nur für Relais welche mit einer vorgegebenen Zeit eingeschaltet werden und mit Sonnenaufgang ausgeschaltet werden. Bei Relais mit einer vorgegebenen Zeit z. B. 18:00 Uhr eingeschalten und um 23:30 Uhr ausgeschalten, geht auch das update in der GUI. Das ganze ist reproduzierbar, mache ich so täglich. Hängt vielleicht auch mit dem Sonnenuntergang / Sonnenaufgangs Bug zusammen. Möchte nur darauf hinweisen.

**Comment by agent4788** [comment]
Der Fehler ist bereits behoben, dazu gab es nur keinen Issue. Bei den Ereignissen wurde der Status nach dem ausführen nicht gespeichert.
