### ISSUE TITLE
XML Error

### ISSUE THREAD

**Issue by Linusten** [agent4788/SHC_Framework#8]
![unbenannt](https://cloud.githubusercontent.com/assets/9747039/5267903/265211b6-7a55-11e4-96f1-b8a7264b73a6.JPG)

Wird auf jeder seite angezeigt wo man Zimmer aufruft

**Comment by agent4788** [comment]
Das Problem habe ich auch manchmal, da wurde die switchables.xml als Leere Datei geschrieben. Entweder kannst du die wieder herstellen aus einer Sicherung, oder musst alles neu Anlegen.

Die Ursache konnte ich aber noch nicht finden, es kann aber nur etwas mit der SD Karte (Schreibgeschindigkeit) o.ä. sein da es auf meinem PC auf dem ich das SHC entwickle nie passiert (der hat aber eine SSD)

**Comment by agent4788** [comment]
mit der Version 2.0.3 kommt der Fix der den Großteil dieser Fehler beheben wird.
