### ISSUE TITLE
Pilight Protokolle auf Pilight Version 7 anpassen

### ISSUE THREAD

**Issue by agent4788** [agent4788/SHC_Framework#84]

**Comment by jsp-email** [comment]
Das blöde an pilight ist es kommt immer wieder neue versionen
Kann man das nicht festlegen zb immer v 6 benutzen

**Comment by agent4788** [comment]
Die pilight versionen kommen ja recht oft und bringen auch neue protokolle. Da wäre es unklug auf alte versionen zu setzen
