### ISSUE TITLE
Administration ohne Anmeldung möglich

### ISSUE THREAD

**Issue by Microgamer** [agent4788/SHC_Framework#93]
Hallo Agent,

meinen Kollegen ist über Tab-Syncronisation aufgefallen, dass man in spezielle Einstellungen kommt, wenn man den Link auf die Seite hat. Änderungen sind auch möglich. Hoffe du kannst das noch mit der 2.2.1 ändern, da es (besonders in unserem Fall) sehr riskant ist, diese Lücke offen zu haben. Musst eigentlich nur immer abfragen, ob man angemeldet ist oder nicht.

Gruß
Microgamer

**Comment by Microgamer** [comment]
Rechte vom Gast sind übrigens komplett aus...

**Comment by agent4788** [comment]
Habt ihr das Synchronisieren der Cookies aktiviert? Wenn ja, kann das RWF Framework, welches sich um die Session Behandlung kümmert, nicht erkennen. Eventuell sollte es gehen wenn der dauerhafte Login deaktiviert wird, das müsst ihr aber probieren (unter Einstellungen > Allgemein > Langzeit Login).

**Comment by Microgamer** [comment]
Langzeit login wurde nicht benutzt und cookies werden nicht synchronisiert.
Ich probiere es morgen mal aus. Leider ist der Tunnelserver aus, weil es ein Fehlverhalten vom RAID Controller gab und so alle Festplatten formatiert wurden. Naja jetzt steigen wir auf Ubuntu-Server. Dann jetzt mal ne Frage OT: Muss auf nem Slave auch der sheduler laufen??

**Comment by agent4788** [comment]
Nur wenn die passenden Session Cookies Synchronisiert werden kann das so passieren. Ohne das Cookie ist man automatisch Gast. Der Slave braucht keinen Sheduler.

**Comment by Microgamer** [comment]
Es werden nur die offenen Tabs und der Verlauf synchronisiert! Oben in der Ecke steht, dass man nicht eingeloggt ist. Du kannst es ja mal probieren, indem du dir den Link von ner Einstellungsseite kopierst, dich dann abmeldest und auf den kopierten Link gehst. Das hat ja den selben Effekt. Du kannst Sachen auf dieser Seite ändern. Wenn das nicht geht, weiß ich auch nicht weiter.

**Comment by agent4788** [comment]
Das ist bei mir auch, normal muss in dem Fall eine AccessDenied Exception kommen. Fix kommt mit 2.2.1

**Comment by Microgamer** [comment]
Supi. Das war das, was ich gemeint habe :+1:
